# Generated by Django 2.2.7 on 2019-12-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='pending_approval',
            field=models.BooleanField(default=True),
        ),
    ]
