# Generated by Django 2.2.7 on 2019-12-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventix', '0002_auto_20191227_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='author',
            new_name='organiser',
        ),
    ]
