# Generated by Django 2.2.7 on 2020-01-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventix', '0003_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventix.Location'),
        ),
    ]
