# Generated by Django 2.2.7 on 2020-01-18 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventix', '0004_auto_20200117_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='event_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seat',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventix.Location'),
        ),
    ]
