# Generated by Django 2.2.7 on 2020-01-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventix', '0004_auto_20200118_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
