# Generated by Django 2.2.7 on 2020-01-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventix', '0004_auto_20200117_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='maximum_number_of_seats',
        ),
        migrations.AddField(
            model_name='location',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seat',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventix.Location'),
        ),
    ]
