# Generated by Django 2.2.7 on 2020-01-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventix', '0005_auto_20200118_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='maximum_number_of_seats',
        ),
        migrations.AddField(
            model_name='location',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
