# Generated by Django 2.2.7 on 2020-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventix', '0006_auto_20200118_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='reserved_to',
        ),
        migrations.AddField(
            model_name='userevent',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
