# Generated by Django 2.2.7 on 2020-01-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventix', '0006_recommendedevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendedEvent',
        ),
    ]
