# Generated by Django 2.2.7 on 2020-01-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventix', '0005_auto_20200118_1815'),
        ('eventix', '0007_auto_20200118_1852'),
        ('eventix', '0005_auto_20200118_1846'),
    ]

    operations = [
    ]
