# Generated by Django 2.2.7 on 2020-01-18 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventix', '0008_merge_20200118_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventix.Event'),
        ),
    ]
