# Generated by Django 2.2.7 on 2019-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_organiser',
            field=models.BooleanField(default=False, help_text='Apply as an event organised'),
        ),
    ]
